"use client";

import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { CalcInfo, type Calculation } from "./calc-info";
import type { Dataset } from "./actions";
import { amount, calculateSummary, REPORT_RATE } from "./finance";

const fmt = (value: unknown, digits = 0) => new Intl.NumberFormat("ru-RU", { maximumFractionDigits: digits, minimumFractionDigits: digits }).format(amount(value));
const som = (value: unknown, digits = 0) => `${fmt(value, digits)} сом`;
const usd = (value: unknown) => value == null ? "Нет курса" : `${fmt(value, 2)} $`;
const box = "rounded-md border border-[#e1e7e4] bg-white";

type Summary = ReturnType<typeof calculateSummary>;
function Metric({ title, value, calculation, emphasis = false, extra }: { title: string; value: string; calculation: Calculation; emphasis?: boolean; extra?: React.ReactNode }) {
  return <div className={`min-w-0 rounded-md border p-4 ${emphasis ? "border-[#c7e0d5] bg-[#eaf5ee]" : "border-[#e1e7e4] bg-white"}`}><div className="flex min-h-5 items-start justify-between gap-2 text-xs text-[#65766c]"><span>{title}</span><CalcInfo {...calculation} /></div><div className={`mt-4 break-words text-lg font-semibold tabular-nums xl:text-xl ${value.startsWith("-") ? "text-[#bb5b4b]" : "text-[#1b352b]"}`}>{value}</div>{extra}</div>;
}
export default function SummaryView({ data, summary: s }: { data: Dataset; summary: Summary }) {
  const rate = s.rate;
  const rateText = rate == null ? "курс не указан" : fmt(rate, 2);
  const base: Calculation = { label: "", formula: "", substitution: "", source: "", excel: "" };
  const breakdown = [
    { label: "Клиенты должны", value: s.clientsOwe, formula: "Σ положительных балансов Клиентов" },
    { label: "Предоплаты клиентов", value: s.clientAdvances, formula: "Σ отрицательных балансов Клиентов" },
    { label: "Партнёры", value: s.partners, formula: "Σ балансов Партнёров" },
    { label: "Заёмщики", value: s.borrowers, formula: "Σ балансов Заёмщиков" },
    { label: "Прочее", value: s.others, formula: "Σ балансов контрагентов типа Прочее" },
  ];
  const months = new Map<string, number>();
  for (const batch of data.batches) if (batch["Дата прибытия"]) {
    const key = new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Bishkek", year: "numeric", month: "2-digit" }).format(new Date(String(batch["Дата прибытия"])));
    months.set(key, (months.get(key) || 0) + amount(batch["Прибыль, сом"]));
  }
  const monthly = [...months].sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => ({ name: key.slice(5) + "." + key.slice(2, 4), value }));
  const debtors = [...data.contacts].filter((row) => row["Тип"] === "Клиент" && amount(row["Баланс"]) > 0).sort((a, b) => amount(b["Баланс"]) - amount(a["Баланс"])).slice(0, 10);
  const stockChart = [...data.products].filter((row) => amount(row["Остаток, кг"]) > 0).sort((a, b) => amount(b["Остаток, кг"]) - amount(a["Остаток, кг"])).slice(0, 10);
  return <>
    <div className="mb-7 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Metric title="Деньги на счетах" value={som(s.accounts)} calculation={{ ...base, label: "Деньги на счетах", formula: "Σ «Остаток» счетов с галочкой «Учитывать в сводке». По Excel в сводку входят РС Эксперт и РС Фудторг (сейчас «Бакай Банк · ОсОО Эксперт» и «Бакай Банк · ОсОО Фудторг»); ИП Мырзабеков и МБ Фудторг — вне сводки.", substitution: `${data.accounts.filter((row) => row["Учитывать в сводке"]).map((row) => som(row["Остаток"], 2)).join(" + ")} = ${som(s.accounts, 2)}`, source: "Счета: Остаток, Учитывать в сводке", excel: "E5 + лист «РС ФУДторг» H2" }} />
      <Metric title="Остаток у контрагентов" value={som(s.counterparts)} calculation={{ ...base, label: "Остаток у контрагентов", formula: "Σ «Баланс» контрагентов типов Клиент, Партнёр, Заёмщик, Прочее.", substitution: `${som(s.clientsOwe, 2)} + (${som(s.clientAdvances, 2)}) + ${som(s.partners, 2)} + ${som(s.borrowers, 2)} + (${som(s.others, 2)}) = ${som(s.counterparts, 2)}`, source: "Контрагенты: Тип, Баланс", excel: "D5 (сумма H2 листов контрагентов)" }} extra={<div className="mt-4 space-y-1 border-t border-[#e6ede8] pt-3">{breakdown.map((part) => <div key={part.label} className="flex items-start justify-between gap-2 text-[11px]"><span className="text-[#74867a]">{part.label}</span><span className="flex items-center gap-1 text-right font-medium tabular-nums">{som(part.value)}<CalcInfo label={part.label} formula={part.formula} substitution={som(part.value, 2)} source="Контрагенты: Тип, Баланс" excel="D5 (составляющая)" /></span></div>)}</div>} />
      <Metric title="Отправлено поставщикам (товар в пути)" value={som(s.inTransit)} calculation={{ ...base, label: "Отправлено поставщикам (товар в пути)", formula: "Σ «Аванс поставщику (в пути)» по партиям со статусом Предоплата/В пути/На таможне.", substitution: `${data.batches.filter((row) => ["Предоплата", "В пути", "На таможне"].includes(String(row["Статус"]))).length} партий = ${som(s.inTransit, 2)}`, source: "Партии: Статус, Аванс поставщику (в пути), сом", excel: "F5 = Китай!T2 + РФ!K2" }} />
      <Metric title="Склад по плановой цене" value={som(s.stock)} calculation={{ ...base, label: "Склад по плановой цене", formula: "Σ «Стоимость остатка» товаров по плановой цене продажи (колонка «цена» складских листов), включая отрицательные значения.", substitution: `${data.products.length} товаров = ${som(s.stock, 2)}`, source: "Товары: Стоимость остатка, сом", excel: "G5 (сумма D2 складских листов)" }} />
    </div>
    <div className="mb-7 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-5">
      <Metric title="ИТОГО ДЕНЕГ В ОБОРОТЕ" value={som(s.turnover)} emphasis calculation={{ ...base, label: "ИТОГО ДЕНЕГ В ОБОРОТЕ", formula: "Деньги на счетах + остаток у контрагентов + отправлено поставщикам + склад.", substitution: `${som(s.accounts, 2)} + ${som(s.counterparts, 2)} + ${som(s.inTransit, 2)} + ${som(s.stock, 2)} = ${som(s.turnover, 2)}`, source: "Счета, Контрагенты, Партии, Товары", excel: "F16" }} extra={<div className="mt-2 flex items-center gap-1 text-xs font-medium text-[#467464]">{usd(s.turnoverUsd)}<CalcInfo label="Оборот, $" formula="ИТОГО ДЕНЕГ В ОБОРОТЕ ÷ курс $ для отчётов" substitution={`${som(s.turnover, 2)} ÷ ${rateText} = ${usd(s.turnoverUsd)}`} source={`Настройки: ${REPORT_RATE}`} excel="F16 (перевод в $)" /></div>} />
      <Metric title="Займы (нетто)" value={som(s.loans)} calculation={{ ...base, label: "Займы (нетто)", formula: "Σ «Баланс» Займодавцев; «+» нам должны, «−» мы должны.", substitution: som(s.loans, 2), source: "Контрагенты: Тип Займодавец, Баланс", excel: "B16 с обратным знаком" }} />
      <Metric title="РАЗНИЦА / ПРИБЫЛЬ (капитал)" value={som(s.capital)} emphasis calculation={{ ...base, label: "РАЗНИЦА / ПРИБЫЛЬ (капитал)", formula: "Оборот + займы (нетто).", substitution: `${som(s.turnover, 2)} + ${som(s.loans, 2)} = ${som(s.capital, 2)}`, source: "ИТОГО ДЕНЕГ В ОБОРОТЕ, Контрагенты: Займодавцы", excel: "I16 = F16 − B16" }} extra={<div className="mt-2 flex items-center gap-1 text-xs font-medium text-[#467464]">{usd(s.capitalUsd)}<CalcInfo label="Капитал, $" formula="Капитал ÷ курс $ для отчётов" substitution={`${som(s.capital, 2)} ÷ ${rateText} = ${usd(s.capitalUsd)}`} source={`Настройки: ${REPORT_RATE}`} excel="J16 = I16 / 88" /></div>} />
      <Metric title="Налоги к уплате" value={som(s.taxes)} calculation={{ ...base, label: "Налоги к уплате", formula: "Σ «Остаток к уплате» таблицы Налоги.", substitution: `${data.taxes.length} начислений = ${som(s.taxes, 2)}`, source: "Налоги: Остаток к уплате, сом", excel: "Расходы!E1" }} />
      <Metric title="РЕАЛЬНЫЙ ОСТАТОК ПОСЛЕ НАЛОГОВ, $" value={usd(s.realUsd)} emphasis calculation={{ ...base, label: "РЕАЛЬНЫЙ ОСТАТОК ПОСЛЕ НАЛОГОВ, $", formula: "(капитал − налоги к уплате) ÷ курс.", substitution: `(${som(s.capital, 2)} − ${som(s.taxes, 2)}) ÷ ${rateText} = ${usd(s.realUsd)}`, source: `Контрагенты, Счета, Партии, Товары, Налоги; Настройки: ${REPORT_RATE}`, excel: "K16" }} />
    </div>
    <div className="mb-7 grid gap-3 sm:grid-cols-3">
      <Metric title="Прибыль по проданным партиям, сом" value={som(s.soldProfitSom)} calculation={{ ...base, label: "Прибыль по проданным партиям, сом", formula: "Σ «Прибыль, сом» по партиям со статусом Продана.", substitution: `${s.soldCount} партий = ${som(s.soldProfitSom, 2)}`, source: "Партии: Статус, Прибыль, сом", excel: "«расчет прибыли» AG" }} />
      <Metric title="Прибыль по проданным партиям, $" value={usd(s.soldProfitUsd)} calculation={{ ...base, label: "Прибыль по проданным партиям, $", formula: "Σ «Прибыль, $» по партиям со статусом Продана.", substitution: `${s.soldCount} партий = ${usd(s.soldProfitUsd)}`, source: "Партии: Статус, Прибыль, $", excel: "«расчет прибыли» AH" }} />
      <Metric title="Средняя маржа проданных партий" value={`${fmt(s.soldMargin, 2)} %`} calculation={{ ...base, label: "Средняя маржа проданных партий", formula: "Σ прибыли проданных партий ÷ Σ выручки проданных партий × 100 (взвешенная по выручке).", substitution: `${som(s.soldProfitSom, 2)} ÷ ${som(data.batches.filter((row) => row["Статус"] === "Продана").reduce((sum, row) => sum + amount(row["Выручка, сом"]), 0), 2)} × 100 = ${fmt(s.soldMargin, 2)} %`, source: "Партии: Статус, Прибыль, сом, Выручка, сом", excel: "«расчет прибыли»: маржа %" }} />
    </div>
    <div className="grid gap-5 xl:grid-cols-2"><div className={`${box} min-w-0 p-5`}><div className="mb-5 flex items-center justify-between gap-2 text-sm font-semibold">Прибыль по партиям<CalcInfo label="Прибыль по партиям по месяцам" formula="Σ «Прибыль, сом» партий по месяцам даты прибытия." substitution={`${monthly.length} месяцев, ${data.batches.length} партий`} source="Партии: Дата прибытия, Прибыль, сом" excel="«расчет прибыли» AG" /></div>{monthly.length ? <div className="h-64"><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{ width: 600, height: 256 }}><BarChart data={monthly} margin={{ top: 4, right: 5, left: -14, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e9eeeb" /><XAxis dataKey="name" tick={{ fontSize: 11, fill: "#84918a" }} axisLine={false} tickLine={false} /><YAxis tickFormatter={(value) => `${fmt(value / 1000000, 1)}м`} tick={{ fontSize: 10, fill: "#84918a" }} axisLine={false} tickLine={false} /><ChartTooltip formatter={(value) => som(value)} /><Bar dataKey="value" fill="#168272" radius={[3, 3, 0, 0]} maxBarSize={34} /></BarChart></ResponsiveContainer></div> : <div className="py-12 text-center text-xs text-[#89968e]">Нет партий с датой прибытия</div>}<div className="mt-2 text-xs text-[#91a099]">По месяцам даты прибытия · сом</div></div>
      <div className={`${box} p-5`}><div className="mb-5 text-sm font-semibold">Топ-10 должников</div>{debtors.length ? <div className="space-y-3">{debtors.map((row, i) => <div key={row.id} className="grid grid-cols-[20px_minmax(0,1fr)_auto] items-center gap-2 text-xs"><span className="text-[#a3aea7]">{i + 1}</span><div className="min-w-0"><div className="truncate text-[#3d5148]">{String(row["Название"] ?? "")}</div><div className="mt-1 h-1.5 rounded-full bg-[#eef2f0]"><div className="h-1.5 rounded-full bg-[#d19b56]" style={{ width: `${Math.max(3, amount(row["Баланс"]) / amount(debtors[0]["Баланс"]) * 100)}%` }} /></div></div><span className="flex items-center gap-1 whitespace-nowrap font-medium tabular-nums">{som(row["Баланс"])}<CalcInfo label={`Баланс: ${String(row["Название"] ?? "")}`} formula="Сальдо на начало + отгрузки в долг − оплаты + выданные ему деньги + авансы за партии в пути." substitution={`${som(row["Сальдо на начало"], 2)} + ${som(row["Отгрузки в долг"], 2)} + ${som(row["Платежи в расчёт"], 2)} + ${som(row["Авансы за партии в пути"], 2)} = ${som(row["Баланс"], 2)}`} source="Контрагенты: Баланс и составляющие" excel="D5 (H2 листа контрагента)" /></span></div>)}</div> : <div className="py-12 text-center text-xs text-[#89968e]">Нет задолженности клиентов</div>}</div>
      <div className={`${box} p-5 xl:col-span-2`}><div className="mb-5 flex items-center justify-between"><div className="text-sm font-semibold">Склад по товарам</div><span className="flex items-center gap-1 text-xs text-[#96a49b]">кг<CalcInfo label="Склад по товарам, кг" formula="Приходы − отгрузки − списания." substitution={`${stockChart.length} товаров с положительным остатком`} source="Товары: Остаток, кг; Движения склада" excel="складские листы: кг (адрес ячейки не указан)" /></span></div>{stockChart.length ? <div className="grid gap-x-10 gap-y-3 md:grid-cols-2">{stockChart.map((row) => <div key={row.id} className="grid grid-cols-[minmax(0,1fr)_auto] gap-2 text-xs"><span className="truncate text-[#54665c]">{String(row["Название"] ?? "")}</span><span className="flex items-center gap-1 font-semibold tabular-nums">{fmt(row["Остаток, кг"])} кг<CalcInfo label={`Остаток: ${String(row["Название"] ?? "")}`} formula="Σ кг приходов − Σ кг отгрузок и списаний." substitution={`${fmt(row["Остаток, кг"], 2)} кг`} source="Товары: Остаток, кг; Движения склада" excel="складской лист товара: кг (адрес ячейки не указан)" /></span><div className="col-span-2 h-2 rounded-full bg-[#eef2ef]"><div className="h-2 rounded-full bg-[#6ca898]" style={{ width: `${Math.max(2, amount(row["Остаток, кг"]) / amount(stockChart[0]["Остаток, кг"]) * 100)}%` }} /></div></div>)}</div> : <div className="py-12 text-center text-xs text-[#89968e]">На складе нет положительных остатков</div>}</div></div>
  </>;
}
